tool
extends Control

onready var fileDialog		= $Panel/FileDialog
onready var optionButton	= $Panel/VBoxContainer/BaseClassSelection/MarginContainer2/OptionButton
onready var pathLabel		= $Panel/VBoxContainer/PathMarginContainer/PathLabel
onready var classNameText	= $Panel/VBoxContainer/ClassNameContainer/ClassNameText

var selected_path
var base_class
var resource_class


func _input(event: InputEvent) -> void:
	if event is InputEventKey\
			and event.scancode == KEY_ESCAPE\
			and event.is_pressed():
		hide()
	


func init(base_classes) -> void:
	optionButton.clear()
	for base in base_classes:
		optionButton.add_item(base)
	
	if base_classes.size():
		base_class = base_classes[0]


func create_script(path, base_class, resource_class) -> void:
	var new_script = GDScript.new()
	new_script.source_code =\
"""# Auto Generated By Resource Editor
tool
extends %s
class_name %s

func get_base(): return "%s"
func get_class(): return "%s"
func is_class(name): return name == "%s" or .is_class(name)
""" % [base_class, resource_class, base_class, resource_class, resource_class]

	ResourceSaver.save(path, new_script)
	LOG.pr(1, "can instance (%s)" % ClassDB.class_exists(resource_class))
#	var dummy_path = "res://src/dummy_data/%s_dummy.tres" % [resource_class]
#	var dummy_res = ClassDB.ge
#	dummy_res.set_script(new_script.duplicate(true))
#	ResourceSaver.save(dummy_path, dummy_res)



func _on_FileDialog_file_selected(path: String) -> void:
	selected_path = path
	pathLabel.text = selected_path



func _on_OptionButton_item_selected(index: int) -> void:
	base_class = optionButton.get_item_text(index)



func _on_SelectFile_pressed() -> void:
	fileDialog.popup()



func _on_CreateButton_pressed() -> void:
	resource_class = classNameText.text
#	LOG.pr(0, "resource_class:(%s)" % [resource_class], "_on_CreateButton_pressed")
	if not resource_class or resource_class.length() == 0:
		return

#	LOG.pr(0, "base_class:(%s) [%s]" % [base_class, optionButton.text], "_on_CreateButton_pressed")
	if not base_class or base_class.length() == 0:
		return

	create_script(selected_path, base_class, resource_class)
	hide()



func _on_Button_pressed() -> void:
	hide()
